name: All Builds (Linux, macOS, Windows, Android, IPA, APK, AAB)

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2
  JAVA_VERSION: '21'

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Setup Java JDK
        if: runner.os == 'Linux' || runner.os == 'Windows'
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

  build:
    runs-on: ${{ matrix.os }}
    needs: setup
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [linux, macos, windows, aab, apk, ipa]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Flet Build ${{ matrix.build_type }}
        run: |
          flutter config --no-analytics
          flet build ${{ matrix.build_type }} --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }}

      - name: Upload ${{ matrix.build_type | toUpperCase }} Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: ${{ matrix.build_type }}-build-artifact
          path: build/${{ matrix.build_type }}
          if-no-files-found: warn
          overwrite: false
