name: Build Flet APK

on:
  push:
    branches:
      - main  # Cambia esto según tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # O la versión que estés usando

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet

    - name: Build APK
      run: |
        pip install pyinstaller
        pyinstaller --onefile main.py --name "nombre_de_tu_apk"  # Cambia el nombre según sea necesario

    - name: Move APK to artifacts
      run: |
        mkdir -p apk
        mv dist/nombre_de_tu_apk apk/  # Asegúrate de que el nombre coincide

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: nombre_de_tu_apk
        path: apk/nombre_de_tu_apk
