name: Build and Install Dependencies

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            portmidi \
            libportmidi-dev \
            libporttime-dev

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      # Si necesitas compilar PortMidi desde el código fuente, descomenta la siguiente sección
      # - name: Install PortMidi from source (if needed)
      #   run: |
      #     git clone https://github.com/PortMidi/portmidi.git
      #     cd portmidi/portmidi
      #     mkdir build
      #     cd build
      #     cmake ..
      #     make
      #     sudo make install
      #     cd ../..
      #     rm -rf portmidi
