name: Build APK for TaskControl

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase flet

      - name: Build the APK
        run: |
          briefcase create android
          briefcase build android
          briefcase package android

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: TaskControl-APK
          path: dist/TaskControl.apk
