name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet briefcase

    - name: Create APK
      run: |
        briefcase create android
        briefcase build android
        briefcase package android

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: TaskControl-APK
        path: dist/android/*
